#! /bin/sh
### BEGIN INIT INFO
# Provides:          MeinProgramm
# Required-Start:    
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts & Stops My Programm
# Description:       Starts & Stops My Programm
### END INIT INFO
 
#Switch case fuer den ersten Parameter
case "$1" in
    start)
 #Aktion wenn start uebergeben wird
        cd /home/pi/Projects/FrameModifier9001/FrameViewer/startScripts/
        ./sendIpStartScript.sh
        echo "setting current ip address"
        ;;
 
    stop)
 #Aktion wenn stop uebergeben wird
        #cd /home/pi/Projects/FrameModifier9001/FrameViewer/startScripts/
        #python send_ip_address_shutdown.py
        #echo "setting bad ip address"
        ;;
 
    restart)
 #Aktion wenn restart uebergeben wird
        echo "Restart"
        ;;
 *)
 #Standard Aktion wenn start|stop|restart nicht passen
 echo "(start|stop|restart)"
 ;;
esac
 
exit 0